export type ElementCategory =
  | "alkali"
  | "alkaline"
  | "transition"
  | "post-transition"
  | "metalloid"
  | "nonmetal"
  | "halogen"
  | "noble"
  | "lanthanide"
  | "actinide"
  | "unknown";

export type Element = {
  z: number;
  symbol: string;
  nameEn: string;
  nameKh: string;
  mass: string;
  config: string;
  category: ElementCategory;
  period: number;
  group: number;
  useEn: string;
  useKh: string;
};

export const CATEGORY_META: Record<
  ElementCategory,
  { en: string; kh: string; cell: string; chip: string; ring: string; text: string; soft: string; family: "metal" | "metalloid" | "nonmetal" }
> = {
  alkali:           { en: "Alkali Metal",       kh: "លោហៈអាល់កាឡាំង",       cell: "bg-rose-100 hover:bg-rose-200 border-rose-300 text-rose-950",         chip: "bg-rose-200 text-rose-900 border-rose-300",         ring: "ring-rose-400",     text: "text-rose-900",     soft: "from-rose-50 to-rose-100",       family: "metal" },
  alkaline:         { en: "Alkaline Earth",     kh: "លោហៈអាល់កាឡាំងទឹក",   cell: "bg-orange-100 hover:bg-orange-200 border-orange-300 text-orange-950", chip: "bg-orange-200 text-orange-900 border-orange-300",   ring: "ring-orange-400",   text: "text-orange-900",   soft: "from-orange-50 to-orange-100",   family: "metal" },
  transition:       { en: "Transition Metal",   kh: "លោហៈផ្លាស់ប្ដូរ",         cell: "bg-amber-100 hover:bg-amber-200 border-amber-300 text-amber-950",     chip: "bg-amber-200 text-amber-900 border-amber-300",       ring: "ring-amber-400",    text: "text-amber-900",    soft: "from-amber-50 to-amber-100",     family: "metal" },
  "post-transition":{ en: "Post-Transition Metal", kh: "លោហៈក្រោយផ្លាស់ប្ដូរ", cell: "bg-lime-100 hover:bg-lime-200 border-lime-300 text-lime-950",         chip: "bg-lime-200 text-lime-900 border-lime-300",         ring: "ring-lime-400",     text: "text-lime-900",     soft: "from-lime-50 to-lime-100",       family: "metal" },
  metalloid:        { en: "Metalloid",          kh: "ពាក់កណ្តាលលោហៈ",      cell: "bg-emerald-100 hover:bg-emerald-200 border-emerald-300 text-emerald-950", chip: "bg-emerald-200 text-emerald-900 border-emerald-300", ring: "ring-emerald-400",  text: "text-emerald-900",  soft: "from-emerald-50 to-emerald-100", family: "metalloid" },
  nonmetal:         { en: "Nonmetal",           kh: "មិនមែនលោហៈ",           cell: "bg-teal-100 hover:bg-teal-200 border-teal-300 text-teal-950",         chip: "bg-teal-200 text-teal-900 border-teal-300",         ring: "ring-teal-400",     text: "text-teal-900",     soft: "from-teal-50 to-teal-100",       family: "nonmetal" },
  halogen:          { en: "Halogen",            kh: "ហាឡូហ្សែន",               cell: "bg-sky-100 hover:bg-sky-200 border-sky-300 text-sky-950",             chip: "bg-sky-200 text-sky-900 border-sky-300",             ring: "ring-sky-400",      text: "text-sky-900",      soft: "from-sky-50 to-sky-100",         family: "nonmetal" },
  noble:            { en: "Noble Gas",          kh: "ឧស្ម័នអភិជន",            cell: "bg-indigo-100 hover:bg-indigo-200 border-indigo-300 text-indigo-950", chip: "bg-indigo-200 text-indigo-900 border-indigo-300",   ring: "ring-indigo-400",   text: "text-indigo-900",   soft: "from-indigo-50 to-indigo-100",   family: "nonmetal" },
  lanthanide:       { en: "Lanthanide",         kh: "ឡង់តាណូអ៊ីត",           cell: "bg-fuchsia-100 hover:bg-fuchsia-200 border-fuchsia-300 text-fuchsia-950", chip: "bg-fuchsia-200 text-fuchsia-900 border-fuchsia-300", ring: "ring-fuchsia-400", text: "text-fuchsia-900",  soft: "from-fuchsia-50 to-fuchsia-100", family: "metal" },
  actinide:         { en: "Actinide",           kh: "អាក់ទីណូអ៊ីត",            cell: "bg-purple-100 hover:bg-purple-200 border-purple-300 text-purple-950", chip: "bg-purple-200 text-purple-900 border-purple-300",   ring: "ring-purple-400",   text: "text-purple-900",   soft: "from-purple-50 to-purple-100",   family: "metal" },
  unknown:          { en: "Unknown",            kh: "មិនស្គាល់",                cell: "bg-stone-100 hover:bg-stone-200 border-stone-300 text-stone-950",     chip: "bg-stone-200 text-stone-900 border-stone-300",       ring: "ring-stone-400",    text: "text-stone-900",    soft: "from-stone-50 to-stone-100",     family: "metal" },
};

// Compact element list. Khmer names use either established Khmer terms (where they exist)
// or transliteration of the English name. Uses are written for Cambodian secondary students.
export const ELEMENTS: Element[] = [
  { z:1,   symbol:"H",  nameEn:"Hydrogen",     nameKh:"អ៊ីដ្រូសែន",          mass:"1.008",   config:"1s¹",                        category:"nonmetal",       period:1, group:1,  useEn:"Lifts balloons; combines with oxygen to make water; future clean fuel.", useKh:"ផុសប៉េងប៉ោង; ផ្សំជាមួយអុកស៊ីសែនបង្កើតទឹក; ឥន្ធនៈស្អាតនៃអនាគត។" },
  { z:2,   symbol:"He", nameEn:"Helium",       nameKh:"អេលីយ៉ូម",            mass:"4.003",   config:"1s²",                        category:"noble",          period:1, group:18, useEn:"Fills party balloons; makes voices high-pitched; cools MRI magnets.",  useKh:"បំពេញប៉េងប៉ោងពិធីបុណ្យ; ធ្វើឲ្យសំឡេងស្រួចស្រាវ; ត្រជាក់មេដែកម៉ាស៊ីន MRI។" },
  { z:3,   symbol:"Li", nameEn:"Lithium",      nameKh:"លីចូម",               mass:"6.94",    config:"[He] 2s¹",                   category:"alkali",         period:2, group:1,  useEn:"Powers phone and electric-car batteries.",                              useKh:"ផ្ដល់ថាមពលថ្មទូរស័ព្ទ និងរថយន្តអគ្គិសនី។" },
  { z:4,   symbol:"Be", nameEn:"Beryllium",    nameKh:"ប៊ែរីលីយ៉ូម",          mass:"9.012",   config:"[He] 2s²",                   category:"alkaline",       period:2, group:2,  useEn:"Used in aerospace alloys and X-ray windows.",                            useKh:"ប្រើក្នុងលោហៈចម្រុះអាកាសចរណ៍ និងបង្អួចកាំរស្មីX។" },
  { z:5,   symbol:"B",  nameEn:"Boron",        nameKh:"បូរ៉ុង",                mass:"10.81",   config:"[He] 2s² 2p¹",               category:"metalloid",      period:2, group:13, useEn:"Used in heat-resistant glass (Pyrex) and detergents.",                  useKh:"ប្រើក្នុងកញ្ចក់ធន់នឹងកំដៅ (Pyrex) និងសាប៊ូ។" },
  { z:6,   symbol:"C",  nameEn:"Carbon",       nameKh:"កាបូន",               mass:"12.01",   config:"[He] 2s² 2p²",               category:"nonmetal",       period:2, group:14, useEn:"The backbone of all life; diamond and graphite are pure carbon.",       useKh:"ឆ្អឹងខ្នងនៃជីវិតទាំងអស់; ពេជ្រ និងក្រាហ្វីត គឺកាបូនបរិសុទ្ធ។" },
  { z:7,   symbol:"N",  nameEn:"Nitrogen",     nameKh:"អាសូត",              mass:"14.01",   config:"[He] 2s² 2p³",               category:"nonmetal",       period:2, group:15, useEn:"78% of the air; key ingredient in fertilizer for rice fields.",         useKh:"៧៨% នៃខ្យល់; គ្រឿងផ្សំសំខាន់នៃជីសម្រាប់វាលស្រែ។" },
  { z:8,   symbol:"O",  nameEn:"Oxygen",       nameKh:"អុកស៊ីសែន",           mass:"16.00",   config:"[He] 2s² 2p⁴",               category:"nonmetal",       period:2, group:16, useEn:"What we breathe; supports fire; combines with hydrogen to make water.", useKh:"ខ្យល់ដែលយើងដកដង្ហើម; ជួយឲ្យភ្លើងឆេះ; ផ្សំជាមួយអ៊ីដ្រូសែនបង្កើតទឹក។" },
  { z:9,   symbol:"F",  nameEn:"Fluorine",     nameKh:"ហ្វ្លុយអូរ",            mass:"19.00",   config:"[He] 2s² 2p⁵",               category:"halogen",        period:2, group:17, useEn:"Added to toothpaste to protect teeth from cavities.",                   useKh:"បន្ថែមក្នុងថ្នាំដុសធ្មេញ ការពារធ្មេញពីការពុក។" },
  { z:10,  symbol:"Ne", nameEn:"Neon",         nameKh:"នេអុង",               mass:"20.18",   config:"[He] 2s² 2p⁶",               category:"noble",          period:2, group:18, useEn:"Glows orange-red in advertising signs.",                                useKh:"ភ្លឺពណ៌ទឹកក្រូចក្រហមនៅលើផ្ទាំងផ្សព្វផ្សាយពាណិជ្ជកម្ម។" },
  { z:11,  symbol:"Na", nameEn:"Sodium",       nameKh:"សូដ្យូម",              mass:"22.99",   config:"[Ne] 3s¹",                   category:"alkali",         period:3, group:1,  useEn:"Half of table salt (NaCl); explosive in pure form.",                    useKh:"ពាក់កណ្តាលនៃអំបិលបាយ (NaCl); ផ្ទុះក្នុងទម្រង់បរិសុទ្ធ។" },
  { z:12,  symbol:"Mg", nameEn:"Magnesium",    nameKh:"ម៉ាញ៉េស្យូម",          mass:"24.31",   config:"[Ne] 3s²",                   category:"alkaline",       period:3, group:2,  useEn:"Burns with brilliant white light; light alloy in laptops and bikes.",   useKh:"ឆេះជាមួយពន្លឺសភ្លឺ; លោហៈស្រាលក្នុងកុំព្យូទ័រយួរដៃ និងកង់។" },
  { z:13,  symbol:"Al", nameEn:"Aluminum",     nameKh:"អាលុយមីញ៉ូម",        mass:"26.98",   config:"[Ne] 3s² 3p¹",               category:"post-transition",period:3, group:13, useEn:"Cans, foil, window frames; light, cheap, recyclable.",                  useKh:"កំប៉ុង ស្បៃ ស៊ុមបង្អួច; ស្រាល ថោក និងអាចកែច្នៃឡើងវិញ។" },
  { z:14,  symbol:"Si", nameEn:"Silicon",      nameKh:"ស៊ីលីស្យូម",            mass:"28.09",   config:"[Ne] 3s² 3p²",               category:"metalloid",      period:3, group:14, useEn:"The brain of every computer chip and solar panel.",                     useKh:"ខួរក្បាលនៃរាល់ឈីបកុំព្យូទ័រ និងផ្ទាំងសូឡា។" },
  { z:15,  symbol:"P",  nameEn:"Phosphorus",   nameKh:"ផូស្វ័រ",              mass:"30.97",   config:"[Ne] 3s² 3p³",               category:"nonmetal",       period:3, group:15, useEn:"In matchsticks, fertilizer, and bones.",                                useKh:"នៅក្នុងឈើគូស ជី និងឆ្អឹង។" },
  { z:16,  symbol:"S",  nameEn:"Sulfur",       nameKh:"ស្ពាន់ធ័រ",            mass:"32.07",   config:"[Ne] 3s² 3p⁴",               category:"nonmetal",       period:3, group:16, useEn:"Yellow and stinky; used in matches, gunpowder, and tire rubber.",       useKh:"លឿង និងស្អុយ; ប្រើក្នុងឈើគូស គ្រាប់កាំភ្លើង និងកៅស៊ូកង់រថយន្ត។" },
  { z:17,  symbol:"Cl", nameEn:"Chlorine",     nameKh:"ក្លរ",                  mass:"35.45",   config:"[Ne] 3s² 3p⁵",               category:"halogen",        period:3, group:17, useEn:"Disinfects swimming pools and drinking water.",                         useKh:"សម្លាប់មេរោគក្នុងអាងហែលទឹក និងទឹកផឹក។" },
  { z:18,  symbol:"Ar", nameEn:"Argon",        nameKh:"អាហ្គន",              mass:"39.95",   config:"[Ne] 3s² 3p⁶",               category:"noble",          period:3, group:18, useEn:"Fills incandescent light bulbs and protects welding arcs.",             useKh:"បំពេញអំពូលភ្លើង និងការពារការផ្សារដែក។" },
  { z:19,  symbol:"K",  nameEn:"Potassium",    nameKh:"ប៉ូតាស្យូម",            mass:"39.10",   config:"[Ar] 4s¹",                   category:"alkali",         period:4, group:1,  useEn:"Bananas are rich in it; vital for nerves and muscles.",                 useKh:"ចេកសម្បូរទៅដោយវា; សំខាន់សម្រាប់សរសៃប្រសាទ និងសាច់ដុំ។" },
  { z:20,  symbol:"Ca", nameEn:"Calcium",      nameKh:"កាល់ស្យូម",            mass:"40.08",   config:"[Ar] 4s²",                   category:"alkaline",       period:4, group:2,  useEn:"Builds strong bones and teeth; main mineral in chalk and milk.",        useKh:"សាងសង់ឆ្អឹង និងធ្មេញរឹងមាំ; សារធាតុរ៉ែសំខាន់ក្នុងដីសរ និងទឹកដោះគោ។" },
  { z:21,  symbol:"Sc", nameEn:"Scandium",     nameKh:"ស្កង់ឌ្យូម",           mass:"44.96",   config:"[Ar] 3d¹ 4s²",               category:"transition",     period:4, group:3,  useEn:"Used in lightweight aluminum alloys for bike frames.",                  useKh:"ប្រើក្នុងលោហៈអាលុយមីញ៉ូមស្រាលសម្រាប់ស៊ុមកង់។" },
  { z:22,  symbol:"Ti", nameEn:"Titanium",     nameKh:"ទីតាន",               mass:"47.87",   config:"[Ar] 3d² 4s²",               category:"transition",     period:4, group:4,  useEn:"Strong yet light — used in aircraft and medical implants.",             useKh:"រឹងមាំប៉ុន្តែស្រាល — ប្រើក្នុងយន្តហោះ និងគ្រឿងវេជ្ជសាស្ត្រ។" },
  { z:23,  symbol:"V",  nameEn:"Vanadium",     nameKh:"វ៉ាណាដ្យូម",           mass:"50.94",   config:"[Ar] 3d³ 4s²",               category:"transition",     period:4, group:5,  useEn:"Strengthens steel for tools and vehicles.",                             useKh:"ពង្រឹងដែកសម្រាប់ឧបករណ៍ និងយានយន្ត។" },
  { z:24,  symbol:"Cr", nameEn:"Chromium",     nameKh:"ក្រូម",                 mass:"52.00",   config:"[Ar] 3d⁵ 4s¹",               category:"transition",     period:4, group:6,  useEn:"Shiny chrome plating on motorbikes and faucets.",                       useKh:"ស្រទាប់ភ្លឺលើម៉ូតូ និងគ្រាប់រ៉ូប៊ីណេ។" },
  { z:25,  symbol:"Mn", nameEn:"Manganese",    nameKh:"ម៉ង់ហ្គាណែស",         mass:"54.94",   config:"[Ar] 3d⁵ 4s²",               category:"transition",     period:4, group:7,  useEn:"Hardens steel; found in dry-cell batteries.",                           useKh:"ធ្វើឲ្យដែករឹង; មាននៅក្នុងថ្មគោល។" },
  { z:26,  symbol:"Fe", nameEn:"Iron",         nameKh:"ដែក",                  mass:"55.85",   config:"[Ar] 3d⁶ 4s²",               category:"transition",     period:4, group:8,  useEn:"Backbone of bridges, cars and tools; carries oxygen in your blood.",     useKh:"ឆ្អឹងខ្នងនៃស្ពាន រថយន្ត និងឧបករណ៍; ដឹកអុកស៊ីសែនក្នុងឈាមរបស់អ្នក។" },
  { z:27,  symbol:"Co", nameEn:"Cobalt",       nameKh:"កូបាល់",                mass:"58.93",   config:"[Ar] 3d⁷ 4s²",               category:"transition",     period:4, group:9,  useEn:"Blue pigment in pottery; key metal in EV batteries.",                   useKh:"ពណ៌ខៀវក្នុងគ្រឿងឆ្នាំង; លោហៈសំខាន់ក្នុងថ្មរថយន្តអគ្គិសនី។" },
  { z:28,  symbol:"Ni", nameEn:"Nickel",       nameKh:"នីកែល",                mass:"58.69",   config:"[Ar] 3d⁸ 4s²",               category:"transition",     period:4, group:10, useEn:"Stainless steel and rechargeable batteries.",                           useKh:"ដែកមិនជូររ និងថ្មសាកថ្មីបាន។" },
  { z:29,  symbol:"Cu", nameEn:"Copper",       nameKh:"ស្ពាន់",                mass:"63.55",   config:"[Ar] 3d¹⁰ 4s¹",              category:"transition",     period:4, group:11, useEn:"Best affordable conductor — wires every house's electricity.",          useKh:"អ្នកនាំខ្សែភ្លើងល្អបំផុតក្នុងតម្លៃសមរម្យ — ខ្សែភ្លើងគ្រប់ផ្ទះ។" },
  { z:30,  symbol:"Zn", nameEn:"Zinc",         nameKh:"ស័ង្កសី",               mass:"65.38",   config:"[Ar] 3d¹⁰ 4s²",              category:"transition",     period:4, group:12, useEn:"Coats steel roofing to prevent rust; in vitamins.",                     useKh:"ស្រោបដំបូលដែក ការពារមិនឲ្យច្រែះ; មាននៅក្នុងវីតាមីន។" },
  { z:31,  symbol:"Ga", nameEn:"Gallium",      nameKh:"កាលីយ៉ូម",            mass:"69.72",   config:"[Ar] 3d¹⁰ 4s² 4p¹",          category:"post-transition",period:4, group:13, useEn:"Melts in your hand; in LED lights and phone chips.",                    useKh:"រលាយក្នុងដៃរបស់អ្នក; មាននៅក្នុងភ្លើង LED និងឈីបទូរស័ព្ទ។" },
  { z:32,  symbol:"Ge", nameEn:"Germanium",    nameKh:"សែរម៉ានីយ៉ូម",        mass:"72.63",   config:"[Ar] 3d¹⁰ 4s² 4p²",          category:"metalloid",      period:4, group:14, useEn:"Used in fiber-optic cables for fast internet.",                         useKh:"ប្រើក្នុងខ្សែកាបអុបទិកសម្រាប់អ៊ីនធឺណិតលឿន។" },
  { z:33,  symbol:"As", nameEn:"Arsenic",      nameKh:"អាសេនិច",            mass:"74.92",   config:"[Ar] 3d¹⁰ 4s² 4p³",          category:"metalloid",      period:4, group:15, useEn:"Famous poison; tiny amounts in some semiconductors.",                  useKh:"ថ្នាំពុលដ៏ល្បី; បរិមាណតិចតួចក្នុងសារធាតុពាក់កណ្តាលអ្នកនាំ។" },
  { z:34,  symbol:"Se", nameEn:"Selenium",     nameKh:"សេលេញ៉ូម",            mass:"78.97",   config:"[Ar] 3d¹⁰ 4s² 4p⁴",          category:"nonmetal",       period:4, group:16, useEn:"Used in solar cells and dandruff shampoo.",                              useKh:"ប្រើក្នុងកោសិកាសូឡា និងសាប៊ូលាងសក់ប្រឆាំងស្បែកក្បាល។" },
  { z:35,  symbol:"Br", nameEn:"Bromine",      nameKh:"ប្រូម",                 mass:"79.90",   config:"[Ar] 3d¹⁰ 4s² 4p⁵",          category:"halogen",        period:4, group:17, useEn:"Reddish-brown liquid; flame retardant in electronics.",                  useKh:"វត្ថុរាវពណ៌ត្នោតក្រហម; ប្រឆាំងភ្លើងក្នុងគ្រឿងអេឡិចត្រូនិក។" },
  { z:36,  symbol:"Kr", nameEn:"Krypton",      nameKh:"ក្រីបតុង",              mass:"83.80",   config:"[Ar] 3d¹⁰ 4s² 4p⁶",          category:"noble",          period:4, group:18, useEn:"Used in high-performance flashlights and photography flash.",            useKh:"ប្រើក្នុងភ្លើងពិល និងពន្លឺម៉ាស៊ីនថត។" },
  { z:37,  symbol:"Rb", nameEn:"Rubidium",     nameKh:"រុយប៊ីដ្យូម",            mass:"85.47",   config:"[Kr] 5s¹",                   category:"alkali",         period:5, group:1,  useEn:"Used in atomic clocks and research lasers.",                            useKh:"ប្រើក្នុងនាឡិកាអាតូម និងឡាស៊ែរស្រាវជ្រាវ។" },
  { z:38,  symbol:"Sr", nameEn:"Strontium",    nameKh:"ស្ត្រុនទីយ៉ូម",          mass:"87.62",   config:"[Kr] 5s²",                   category:"alkaline",       period:5, group:2,  useEn:"Bright red in fireworks.",                                              useKh:"ពណ៌ក្រហមភ្លឺក្នុងកាំជ្រួច។" },
  { z:39,  symbol:"Y",  nameEn:"Yttrium",      nameKh:"អ៊ីទ្រីយ៉ូម",            mass:"88.91",   config:"[Kr] 4d¹ 5s²",               category:"transition",     period:5, group:3,  useEn:"Red phosphor in older TV screens; in LEDs.",                            useKh:"សារធាតុបញ្ចេញពន្លឺក្រហមក្នុងអេក្រង់ទូរទស្សន៍ចាស់; មាននៅក្នុងភ្លើង LED។" },
  { z:40,  symbol:"Zr", nameEn:"Zirconium",    nameKh:"ហ្ស៊ីកូនីយ៉ូម",         mass:"91.22",   config:"[Kr] 4d² 5s²",               category:"transition",     period:5, group:4,  useEn:"Cubic zirconia mimics diamonds; nuclear reactor cladding.",             useKh:"គូប៊ីក ហ្ស៊ីកូនៀ ធ្វើត្រាប់តាមពេជ្រ; ស្រោបរ៉េអាក់ទ័រនុយក្លេអ៊ែរ។" },
  { z:41,  symbol:"Nb", nameEn:"Niobium",      nameKh:"នីយ៉ូប៊ីយ៉ូម",            mass:"92.91",   config:"[Kr] 4d⁴ 5s¹",               category:"transition",     period:5, group:5,  useEn:"Used in superconducting magnets for MRI machines.",                     useKh:"ប្រើក្នុងមេដែកអ្នកនាំខ្ពស់សម្រាប់ម៉ាស៊ីន MRI។" },
  { z:42,  symbol:"Mo", nameEn:"Molybdenum",   nameKh:"ម៉ូលីបដែន",            mass:"95.95",   config:"[Kr] 4d⁵ 5s¹",               category:"transition",     period:5, group:6,  useEn:"Strengthens steel in jet engines and rifles.",                          useKh:"ពង្រឹងដែកក្នុងម៉ាស៊ីនយន្ដហោះ និងកាំភ្លើង។" },
  { z:43,  symbol:"Tc", nameEn:"Technetium",   nameKh:"តិចណេទីយ៉ូម",        mass:"(98)",    config:"[Kr] 4d⁵ 5s²",               category:"transition",     period:5, group:7,  useEn:"Radioactive; used in medical imaging scans.",                          useKh:"មានវិទ្យុសកម្ម; ប្រើក្នុងការស្កេនរូបភាពវេជ្ជសាស្ត្រ។" },
  { z:44,  symbol:"Ru", nameEn:"Ruthenium",    nameKh:"រូតេញ៉ូម",              mass:"101.07",  config:"[Kr] 4d⁷ 5s¹",               category:"transition",     period:5, group:8,  useEn:"Hardens platinum jewelry and electrical contacts.",                     useKh:"ធ្វើឲ្យគ្រឿងអលង្ការផ្លាទីនរឹង និងចំណុចទាក់ទងអគ្គិសនី។" },
  { z:45,  symbol:"Rh", nameEn:"Rhodium",      nameKh:"រ៉ូដ្យូម",                mass:"102.91",  config:"[Kr] 4d⁸ 5s¹",               category:"transition",     period:5, group:9,  useEn:"Most precious metal; used in catalytic converters of cars.",            useKh:"លោហៈមានតម្លៃបំផុត; ប្រើក្នុងឧបករណ៍កាតាលីករនៃរថយន្ត។" },
  { z:46,  symbol:"Pd", nameEn:"Palladium",    nameKh:"ប៉ាឡាដ្យូម",            mass:"106.42",  config:"[Kr] 4d¹⁰",                  category:"transition",     period:5, group:10, useEn:"Catalytic converters; jewelry.",                                       useKh:"ឧបករណ៍កាតាលីករ; គ្រឿងអលង្ការ។" },
  { z:47,  symbol:"Ag", nameEn:"Silver",       nameKh:"ប្រាក់",                 mass:"107.87",  config:"[Kr] 4d¹⁰ 5s¹",              category:"transition",     period:5, group:11, useEn:"Best electrical conductor; jewelry, mirrors, and photo film.",          useKh:"អ្នកនាំខ្សែភ្លើងល្អបំផុត; គ្រឿងអលង្ការ កញ្ចក់ និងហ្វីលរូបថត។" },
  { z:48,  symbol:"Cd", nameEn:"Cadmium",      nameKh:"កាដ្យូម",               mass:"112.41",  config:"[Kr] 4d¹⁰ 5s²",              category:"transition",     period:5, group:12, useEn:"In NiCd batteries and yellow paint pigments; toxic.",                   useKh:"នៅក្នុងថ្ម NiCd និងថ្នាំលាបពណ៌លឿង; ពុល។" },
  { z:49,  symbol:"In", nameEn:"Indium",       nameKh:"អាំងដ្យូម",              mass:"114.82",  config:"[Kr] 4d¹⁰ 5s² 5p¹",          category:"post-transition",period:5, group:13, useEn:"Touch-screen coatings on smartphones.",                                useKh:"ស្រទាប់អេក្រង់ប៉ះនៅលើស្មាតហ្វូន។" },
  { z:50,  symbol:"Sn", nameEn:"Tin",          nameKh:"សំណប៉ាហាំង",           mass:"118.71",  config:"[Kr] 4d¹⁰ 5s² 5p²",          category:"post-transition",period:5, group:14, useEn:"Coats food cans; one half of solder for electronics.",                  useKh:"ស្រោបកំប៉ុងម្ហូប; ផ្នែកពាក់កណ្តាលនៃការផ្សារសម្រាប់គ្រឿងអេឡិចត្រូនិក។" },
  { z:51,  symbol:"Sb", nameEn:"Antimony",     nameKh:"អង់ទីម៉ូន",             mass:"121.76",  config:"[Kr] 4d¹⁰ 5s² 5p³",          category:"metalloid",      period:5, group:15, useEn:"Flame retardant in mattresses and circuit boards.",                     useKh:"ប្រឆាំងភ្លើងក្នុងពូក និងបន្ទះវង់ភ្លើង។" },
  { z:52,  symbol:"Te", nameEn:"Tellurium",    nameKh:"តេលូរីយ៉ូម",            mass:"127.60",  config:"[Kr] 4d¹⁰ 5s² 5p⁴",          category:"metalloid",      period:5, group:16, useEn:"In thin-film solar panels and rewritable DVDs.",                       useKh:"ក្នុងផ្ទាំងសូឡាហ្វីលស្ដើង និងឌីវីឌីសរសេរឡើងវិញ។" },
  { z:53,  symbol:"I",  nameEn:"Iodine",       nameKh:"អ៊ីយ៉ូត",                mass:"126.90",  config:"[Kr] 4d¹⁰ 5s² 5p⁵",          category:"halogen",        period:5, group:17, useEn:"Antiseptic for wounds; added to salt to prevent goiter.",               useKh:"ថ្នាំសម្លាប់មេរោគលើរបួស; បន្ថែមក្នុងអំបិលដើម្បីការពារពកក។" },
  { z:54,  symbol:"Xe", nameEn:"Xenon",        nameKh:"សេណុង",               mass:"131.29",  config:"[Kr] 4d¹⁰ 5s² 5p⁶",          category:"noble",          period:5, group:18, useEn:"Bright headlights for cars; ion thrusters in spacecraft.",              useKh:"ពិលមុខរថយន្តភ្លឺ; ម៉ាស៊ីនរុញអ៊ីយ៉ុងក្នុងយានអវកាស។" },
  { z:55,  symbol:"Cs", nameEn:"Cesium",       nameKh:"សេស្យូម",               mass:"132.91",  config:"[Xe] 6s¹",                   category:"alkali",         period:6, group:1,  useEn:"Defines the second in atomic clocks.",                                  useKh:"កំណត់វិនាទីក្នុងនាឡិកាអាតូម។" },
  { z:56,  symbol:"Ba", nameEn:"Barium",       nameKh:"បារីយ៉ូម",                mass:"137.33",  config:"[Xe] 6s²",                   category:"alkaline",       period:6, group:2,  useEn:"Drink-able barium meal helps doctors X-ray your stomach.",              useKh:"ភេសជ្ជៈបារីយ៉ូមជួយវេជ្ជបណ្ឌិតថតកាំរស្មីX ក្រពះរបស់អ្នក។" },
  { z:57,  symbol:"La", nameEn:"Lanthanum",    nameKh:"ឡង់តាន",               mass:"138.91",  config:"[Xe] 5d¹ 6s²",               category:"lanthanide",     period:9, group:3,  useEn:"Camera lens glass and hybrid car batteries.",                          useKh:"កញ្ចក់កាមេរ៉ា និងថ្មរថយន្តកូនកាត់។" },
  { z:58,  symbol:"Ce", nameEn:"Cerium",       nameKh:"សេរីយ៉ូម",              mass:"140.12",  config:"[Xe] 4f¹ 5d¹ 6s²",           category:"lanthanide",     period:9, group:4,  useEn:"Self-cleaning ovens and lighter flints.",                              useKh:"ឡដុតខ្លួនឯង និងកាំជ្រួចបង្កាត់ភ្លើង។" },
  { z:59,  symbol:"Pr", nameEn:"Praseodymium", nameKh:"ប្រាសេអូឌីម",         mass:"140.91",  config:"[Xe] 4f³ 6s²",               category:"lanthanide",     period:9, group:5,  useEn:"Welder's goggles; super-strong magnets.",                              useKh:"វ៉ែនតាជាងផ្សារ; មេដែកមាំខ្លាំង។" },
  { z:60,  symbol:"Nd", nameEn:"Neodymium",    nameKh:"នេអូឌីម",              mass:"144.24",  config:"[Xe] 4f⁴ 6s²",               category:"lanthanide",     period:9, group:6,  useEn:"World's strongest permanent magnets — in headphones and motors.",       useKh:"មេដែកអចិន្ត្រៃយ៍មាំបំផុតក្នុងពិភពលោក — ក្នុងកាស និងម៉ូទ័រ។" },
  { z:61,  symbol:"Pm", nameEn:"Promethium",   nameKh:"ប្រូមេទីយ៉ូម",          mass:"(145)",   config:"[Xe] 4f⁵ 6s²",               category:"lanthanide",     period:9, group:7,  useEn:"Radioactive; used in luminous paint for instrument dials.",             useKh:"មានវិទ្យុសកម្ម; ប្រើក្នុងថ្នាំលាបបញ្ចេញពន្លឺសម្រាប់ឧបករណ៍វាស់។" },
  { z:62,  symbol:"Sm", nameEn:"Samarium",     nameKh:"សាម៉ារីយ៉ូម",          mass:"150.36",  config:"[Xe] 4f⁶ 6s²",               category:"lanthanide",     period:9, group:8,  useEn:"High-temperature magnets for missiles.",                                useKh:"មេដែកសម្រាប់សីតុណ្ហភាពខ្ពស់ ប្រើក្នុងគ្រាប់មីស៊ីល។" },
  { z:63,  symbol:"Eu", nameEn:"Europium",     nameKh:"អឺរ៉ុបីយ៉ូម",            mass:"151.96",  config:"[Xe] 4f⁷ 6s²",               category:"lanthanide",     period:9, group:9,  useEn:"Glows red in TV screens; anti-counterfeit ink in euro banknotes.",       useKh:"ភ្លឺពណ៌ក្រហមក្នុងអេក្រង់ទូរទស្សន៍; ទឹកប្រឆាំងក្លែងក្លាយក្នុងក្រដាសប្រាក់អឺរ៉ូ។" },
  { z:64,  symbol:"Gd", nameEn:"Gadolinium",   nameKh:"កាដូលីញ៉ូម",          mass:"157.25",  config:"[Xe] 4f⁷ 5d¹ 6s²",           category:"lanthanide",     period:9, group:10, useEn:"Contrast agent for MRI scans; nuclear reactor control rods.",          useKh:"សារធាតុបន្ថែមភាពច្បាស់សម្រាប់ការស្កេន MRI; ដំបងគ្រប់គ្រងរ៉េអាក់ទ័រនុយក្លេអ៊ែរ។" },
  { z:65,  symbol:"Tb", nameEn:"Terbium",      nameKh:"ទែបីយ៉ូម",              mass:"158.93",  config:"[Xe] 4f⁹ 6s²",               category:"lanthanide",     period:9, group:11, useEn:"Green phosphor in fluorescent lamps and TV displays.",                  useKh:"សារធាតុបញ្ចេញពន្លឺពណ៌បៃតងក្នុងអំពូលនេអុង និងអេក្រង់ទូរទស្សន៍។" },
  { z:66,  symbol:"Dy", nameEn:"Dysprosium",   nameKh:"ឌីសប្រូស្យូម",         mass:"162.50",  config:"[Xe] 4f¹⁰ 6s²",              category:"lanthanide",     period:9, group:12, useEn:"Heat-resistant magnets in electric cars and wind turbines.",            useKh:"មេដែកធន់នឹងកំដៅក្នុងរថយន្តអគ្គិសនី និងកង្ហារខ្យល់។" },
  { z:67,  symbol:"Ho", nameEn:"Holmium",      nameKh:"ហុលមីយ៉ូម",            mass:"164.93",  config:"[Xe] 4f¹¹ 6s²",              category:"lanthanide",     period:9, group:13, useEn:"Strongest magnetic field of any element; medical lasers.",              useKh:"ដែនមេដែកខ្លាំងបំផុតនៃធាតុណាមួយ; ឡាស៊ែរវេជ្ជសាស្ត្រ។" },
  { z:68,  symbol:"Er", nameEn:"Erbium",       nameKh:"អែបីយ៉ូម",              mass:"167.26",  config:"[Xe] 4f¹² 6s²",              category:"lanthanide",     period:9, group:14, useEn:"Boosts long-distance signal in fiber-optic cables.",                    useKh:"ពង្រឹងសញ្ញាចម្ងាយឆ្ងាយក្នុងខ្សែកាបអុបទិក។" },
  { z:69,  symbol:"Tm", nameEn:"Thulium",      nameKh:"តូលីយ៉ូម",              mass:"168.93",  config:"[Xe] 4f¹³ 6s²",              category:"lanthanide",     period:9, group:15, useEn:"X-ray sources for portable medical devices.",                          useKh:"ប្រភពកាំរស្មី X សម្រាប់ឧបករណ៍វេជ្ជសាស្ត្រចល័ត។" },
  { z:70,  symbol:"Yb", nameEn:"Ytterbium",    nameKh:"អ៊ីតែបីយ៉ូម",           mass:"173.05",  config:"[Xe] 4f¹⁴ 6s²",              category:"lanthanide",     period:9, group:16, useEn:"In stress gauges and atomic clocks.",                                  useKh:"ក្នុងឧបករណ៍វាស់សម្ពាធ និងនាឡិកាអាតូម។" },
  { z:71,  symbol:"Lu", nameEn:"Lutetium",     nameKh:"លូតេទីយ៉ូម",           mass:"174.97",  config:"[Xe] 4f¹⁴ 5d¹ 6s²",          category:"lanthanide",     period:9, group:17, useEn:"PET scan detectors; oil refining catalyst.",                            useKh:"ឧបករណ៍ចាប់សញ្ញាការស្កេន PET; កាតាលីករសម្រាប់ប្រេង។" },
  { z:72,  symbol:"Hf", nameEn:"Hafnium",      nameKh:"ហាហ្វនីយ៉ូម",          mass:"178.49",  config:"[Xe] 4f¹⁴ 5d² 6s²",          category:"transition",     period:6, group:4,  useEn:"Used in microchips and nuclear reactor control rods.",                  useKh:"ប្រើក្នុងមីក្រូឈីប និងដំបងគ្រប់គ្រងរ៉េអាក់ទ័រនុយក្លេអ៊ែរ។" },
  { z:73,  symbol:"Ta", nameEn:"Tantalum",     nameKh:"តង់តាល់",               mass:"180.95",  config:"[Xe] 4f¹⁴ 5d³ 6s²",          category:"transition",     period:6, group:5,  useEn:"Capacitors in every smartphone.",                                      useKh:"ឧបករណ៍បន្ថែមថាមពលក្នុងស្មាតហ្វូននីមួយៗ។" },
  { z:74,  symbol:"W",  nameEn:"Tungsten",     nameKh:"ទង់ស្ទែន",              mass:"183.84",  config:"[Xe] 4f¹⁴ 5d⁴ 6s²",          category:"transition",     period:6, group:6,  useEn:"Highest melting point of any metal — used in light-bulb filaments.",     useKh:"ចំណុចរលាយខ្ពស់បំផុតនៃលោហៈណាមួយ — ប្រើក្នុងខ្សែអំពូលភ្លើង។" },
  { z:75,  symbol:"Re", nameEn:"Rhenium",      nameKh:"រេនីយ៉ូម",              mass:"186.21",  config:"[Xe] 4f¹⁴ 5d⁵ 6s²",          category:"transition",     period:6, group:7,  useEn:"Jet engine blades — survives extreme heat.",                            useKh:"ស្លាបម៉ាស៊ីនយន្តហោះ — ស៊ូទ្រាំកំដៅខ្លាំង។" },
  { z:76,  symbol:"Os", nameEn:"Osmium",       nameKh:"អូស្មីយ៉ូម",            mass:"190.23",  config:"[Xe] 4f¹⁴ 5d⁶ 6s²",          category:"transition",     period:6, group:8,  useEn:"Densest natural element; pen-tip nibs.",                               useKh:"ធាតុធម្មជាតិក្រាស់បំផុត; ចុងប៊ិច។" },
  { z:77,  symbol:"Ir", nameEn:"Iridium",      nameKh:"អ៊ីរីដ្យូម",              mass:"192.22",  config:"[Xe] 4f¹⁴ 5d⁷ 6s²",          category:"transition",     period:6, group:9,  useEn:"Spark-plug tips; the asteroid that ended dinosaurs was rich in it.",    useKh:"ចុងប៊ូហ្ស៊ី; ផ្កាយដុះកន្ទុយដែលបានបញ្ចប់ដាយណូស័រសម្បូរទៅដោយវា។" },
  { z:78,  symbol:"Pt", nameEn:"Platinum",     nameKh:"ផ្លាទីន",                mass:"195.08",  config:"[Xe] 4f¹⁴ 5d⁹ 6s¹",          category:"transition",     period:6, group:10, useEn:"Wedding rings; catalytic converters in cars.",                          useKh:"ចិញ្ចៀនអាពាហ៍ពិពាហ៍; ឧបករណ៍កាតាលីករក្នុងរថយន្ត។" },
  { z:79,  symbol:"Au", nameEn:"Gold",         nameKh:"មាស",                  mass:"196.97",  config:"[Xe] 4f¹⁴ 5d¹⁰ 6s¹",         category:"transition",     period:6, group:11, useEn:"Used in electronics and jewelry; never tarnishes.",                    useKh:"ប្រើក្នុងគ្រឿងអេឡិចត្រូនិក និងគ្រឿងអលង្ការ; មិនដែលច្រែះ។" },
  { z:80,  symbol:"Hg", nameEn:"Mercury",      nameKh:"បារត",                  mass:"200.59",  config:"[Xe] 4f¹⁴ 5d¹⁰ 6s²",         category:"transition",     period:6, group:12, useEn:"Liquid metal in old thermometers; toxic.",                              useKh:"លោហៈរាវនៅក្នុងតង់ស្យូសាស្ត្រចាស់; ពុល។" },
  { z:81,  symbol:"Tl", nameEn:"Thallium",     nameKh:"តាល្ល្យូម",              mass:"204.38",  config:"[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p¹",     category:"post-transition",period:6, group:13, useEn:"Once used as rat poison; infrared detectors.",                          useKh:"ធ្លាប់ប្រើជាថ្នាំសម្លាប់កណ្តុរ; ឧបករណ៍ចាប់សញ្ញាអ៊ីនហ្វ្រារ៉េដ។" },
  { z:82,  symbol:"Pb", nameEn:"Lead",         nameKh:"សំណរ",                 mass:"207.20",  config:"[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p²",     category:"post-transition",period:6, group:14, useEn:"Car batteries; X-ray shields; toxic to children.",                      useKh:"ថ្មរថយន្ត; ខែលការពារកាំរស្មី X; ពុលដល់កុមារ។" },
  { z:83,  symbol:"Bi", nameEn:"Bismuth",      nameKh:"ប៊ីស្ម័ត",                mass:"208.98",  config:"[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p³",     category:"post-transition",period:6, group:15, useEn:"Pepto-Bismol stomach medicine; rainbow-colored crystals.",              useKh:"ថ្នាំក្រពះ Pepto-Bismol; គ្រីស្តាល់ពណ៌ឥន្ទធនូ។" },
  { z:84,  symbol:"Po", nameEn:"Polonium",     nameKh:"ប៉ូឡូញ៉ូម",              mass:"(209)",   config:"[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁴",     category:"post-transition",period:6, group:16, useEn:"Radioactive; used in static eliminators.",                              useKh:"មានវិទ្យុសកម្ម; ប្រើក្នុងឧបករណ៍លុបបំបាត់ថាមពលឋិតិវន្ត។" },
  { z:85,  symbol:"At", nameEn:"Astatine",     nameKh:"អាស្តាទីន",             mass:"(210)",   config:"[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁵",     category:"halogen",        period:6, group:17, useEn:"Rarest natural element; potential cancer treatment.",                  useKh:"ធាតុធម្មជាតិកម្របំផុត; ការព្យាបាលជំងឺមហារីកសក្តានុពល។" },
  { z:86,  symbol:"Rn", nameEn:"Radon",        nameKh:"រ៉ាដុង",                  mass:"(222)",   config:"[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁶",     category:"noble",          period:6, group:18, useEn:"Radioactive gas — leading cause of lung cancer in non-smokers.",        useKh:"ឧស្ម័នវិទ្យុសកម្ម — មូលហេតុនាំមុខនៃជំងឺមហារីកសួតក្នុងអ្នកមិនជក់បារី។" },
  { z:87,  symbol:"Fr", nameEn:"Francium",     nameKh:"ហ្វ្រង់ស្យូម",            mass:"(223)",   config:"[Rn] 7s¹",                   category:"alkali",         period:7, group:1,  useEn:"Extremely rare and radioactive; only research use.",                    useKh:"កម្រ និងមានវិទ្យុសកម្មខ្លាំង; ប្រើតែសម្រាប់ការស្រាវជ្រាវ។" },
  { z:88,  symbol:"Ra", nameEn:"Radium",       nameKh:"រ៉ាដ្យូម",                mass:"(226)",   config:"[Rn] 7s²",                   category:"alkaline",       period:7, group:2,  useEn:"Once used in glow-in-the-dark watch dials; banned for being toxic.",     useKh:"ធ្លាប់ប្រើនៅក្នុងមុខនាឡិកាភ្លឺក្នុងងងឹត; ហាមឃាត់ដោយសារពុល។" },
  { z:89,  symbol:"Ac", nameEn:"Actinium",     nameKh:"អាក់ទីញ៉ូម",            mass:"(227)",   config:"[Rn] 6d¹ 7s²",               category:"actinide",       period:10,group:3,  useEn:"Targeted radiation therapy for cancer.",                                useKh:"ការព្យាបាលដោយវិទ្យុសកម្មគោលដៅសម្រាប់ជំងឺមហារីក។" },
  { z:90,  symbol:"Th", nameEn:"Thorium",      nameKh:"តូរីយ៉ូម",                mass:"232.04",  config:"[Rn] 6d² 7s²",               category:"actinide",       period:10,group:4,  useEn:"Potential clean nuclear-reactor fuel.",                                useKh:"ឥន្ធនៈរ៉េអាក់ទ័រនុយក្លេអ៊ែរស្អាតសក្តានុពល។" },
  { z:91,  symbol:"Pa", nameEn:"Protactinium", nameKh:"ប្រូតាក់ទីញ៉ូម",        mass:"231.04",  config:"[Rn] 5f² 6d¹ 7s²",           category:"actinide",       period:10,group:5,  useEn:"Used to date ancient marine sediments.",                                useKh:"ប្រើដើម្បីកំណត់អាយុកំទេចសមុទ្របុរាណ។" },
  { z:92,  symbol:"U",  nameEn:"Uranium",      nameKh:"អ៊ុយរ៉ានីយ៉ូម",         mass:"238.03",  config:"[Rn] 5f³ 6d¹ 7s²",           category:"actinide",       period:10,group:6,  useEn:"Fuel for nuclear power plants and submarines.",                         useKh:"ឥន្ធនៈសម្រាប់រោងចក្រថាមពលនុយក្លេអ៊ែរ និងនាវាមុជទឹក។" },
  { z:93,  symbol:"Np", nameEn:"Neptunium",    nameKh:"នេប៊្យូនីយ៉ូម",         mass:"(237)",   config:"[Rn] 5f⁴ 6d¹ 7s²",           category:"actinide",       period:10,group:7,  useEn:"By-product of nuclear reactors; used in neutron detectors.",            useKh:"ផលិតផលរងពីរ៉េអាក់ទ័រនុយក្លេអ៊ែរ; ប្រើក្នុងឧបករណ៍ចាប់ណឺត្រុង។" },
  { z:94,  symbol:"Pu", nameEn:"Plutonium",    nameKh:"ភ្លុយតូនីយ៉ូម",          mass:"(244)",   config:"[Rn] 5f⁶ 7s²",               category:"actinide",       period:10,group:8,  useEn:"Powers space probes (Voyager, Mars rovers); nuclear weapons.",         useKh:"ផ្តល់ថាមពលដល់យានស្ទង់អវកាស (Voyager, Mars rovers); អាវុធនុយក្លេអ៊ែរ។" },
  { z:95,  symbol:"Am", nameEn:"Americium",    nameKh:"អាម៉េរីស្យូម",          mass:"(243)",   config:"[Rn] 5f⁷ 7s²",               category:"actinide",       period:10,group:9,  useEn:"Inside household smoke detectors.",                                    useKh:"នៅខាងក្នុងឧបករណ៍ចាប់ផ្សែងតាមផ្ទះ។" },
  { z:96,  symbol:"Cm", nameEn:"Curium",       nameKh:"គ្យូរីយ៉ូម",              mass:"(247)",   config:"[Rn] 5f⁷ 6d¹ 7s²",           category:"actinide",       period:10,group:10, useEn:"Power source for spacecraft instruments.",                              useKh:"ប្រភពថាមពលសម្រាប់ឧបករណ៍យានអវកាស។" },
  { z:97,  symbol:"Bk", nameEn:"Berkelium",    nameKh:"ប៊ឺកលីយ៉ូម",            mass:"(247)",   config:"[Rn] 5f⁹ 7s²",               category:"actinide",       period:10,group:11, useEn:"Used to discover heavier synthetic elements.",                          useKh:"ប្រើដើម្បីរកឃើញធាតុសំយោគធ្ងន់ជាងនេះ។" },
  { z:98,  symbol:"Cf", nameEn:"Californium",  nameKh:"កាលីហ្វូនីយ៉ូម",       mass:"(251)",   config:"[Rn] 5f¹⁰ 7s²",              category:"actinide",       period:10,group:12, useEn:"Neutron source for oil-well exploration and cancer therapy.",          useKh:"ប្រភពណឺត្រុងសម្រាប់ការស្វែងរកអណ្តូងប្រេង និងការព្យាបាលមហារីក។" },
  { z:99,  symbol:"Es", nameEn:"Einsteinium",  nameKh:"អ៊ីនស្ទែនីយ៉ូម",       mass:"(252)",   config:"[Rn] 5f¹¹ 7s²",              category:"actinide",       period:10,group:13, useEn:"Discovered in fallout from a hydrogen-bomb test in 1952.",              useKh:"រកឃើញនៅក្នុងធូលីពីការសាកល្បងគ្រាប់បែកអ៊ីដ្រូសែនឆ្នាំ ១៩៥២។" },
  { z:100, symbol:"Fm", nameEn:"Fermium",      nameKh:"ហ្វែមីយ៉ូម",            mass:"(257)",   config:"[Rn] 5f¹² 7s²",              category:"actinide",       period:10,group:14, useEn:"Made only in tiny lab amounts; pure research.",                         useKh:"ផលិតបានតែបរិមាណតិចតួចក្នុងមន្ទីរពិសោធន៍; ការស្រាវជ្រាវសុទ្ធ។" },
  { z:101, symbol:"Md", nameEn:"Mendelevium",  nameKh:"មែនដេលេវីយ៉ូម",       mass:"(258)",   config:"[Rn] 5f¹³ 7s²",              category:"actinide",       period:10,group:15, useEn:"Named for Mendeleev, the periodic-table inventor.",                    useKh:"ដាក់ឈ្មោះតាមមែនដេលេវ ដែលជាអ្នកបង្កើតតារាងខួប។" },
  { z:102, symbol:"No", nameEn:"Nobelium",     nameKh:"ណូបេលីយ៉ូម",           mass:"(259)",   config:"[Rn] 5f¹⁴ 7s²",              category:"actinide",       period:10,group:16, useEn:"Named after Alfred Nobel; pure research only.",                        useKh:"ដាក់ឈ្មោះតាម Alfred Nobel; ការស្រាវជ្រាវសុទ្ធតែប៉ុណ្ណោះ។" },
  { z:103, symbol:"Lr", nameEn:"Lawrencium",   nameKh:"ឡរិនស្យូម",            mass:"(266)",   config:"[Rn] 5f¹⁴ 7s² 7p¹",          category:"actinide",       period:10,group:17, useEn:"Last actinide; only a few atoms have ever existed.",                    useKh:"អាក់ទីណូអ៊ីតចុងក្រោយ; មានតែអាតូមមួយចំនួនប៉ុណ្ណោះដែលធ្លាប់មាន។" },
  { z:104, symbol:"Rf", nameEn:"Rutherfordium",nameKh:"រូទែផតីយ៉ូម",          mass:"(267)",   config:"[Rn] 5f¹⁴ 6d² 7s²",          category:"transition",     period:7, group:4,  useEn:"Synthetic and short-lived; named for Ernest Rutherford.",               useKh:"សំយោគ និងមានជីវិតខ្លី; ដាក់ឈ្មោះតាម Ernest Rutherford។" },
  { z:105, symbol:"Db", nameEn:"Dubnium",      nameKh:"ឌូបនីយ៉ូម",            mass:"(268)",   config:"[Rn] 5f¹⁴ 6d³ 7s²",          category:"transition",     period:7, group:5,  useEn:"Synthetic; named for the Russian city of Dubna.",                       useKh:"សំយោគ; ដាក់ឈ្មោះតាមទីក្រុងឌូបណាប្រទេសរុស្ស៊ី។" },
  { z:106, symbol:"Sg", nameEn:"Seaborgium",   nameKh:"សេបូជីយ៉ូម",          mass:"(269)",   config:"[Rn] 5f¹⁴ 6d⁴ 7s²",          category:"transition",     period:7, group:6,  useEn:"Synthetic; named for Glenn Seaborg.",                                  useKh:"សំយោគ; ដាក់ឈ្មោះតាម Glenn Seaborg។" },
  { z:107, symbol:"Bh", nameEn:"Bohrium",      nameKh:"បូរីយ៉ូម",                mass:"(270)",   config:"[Rn] 5f¹⁴ 6d⁵ 7s²",          category:"transition",     period:7, group:7,  useEn:"Synthetic; named for Niels Bohr.",                                     useKh:"សំយោគ; ដាក់ឈ្មោះតាម Niels Bohr។" },
  { z:108, symbol:"Hs", nameEn:"Hassium",      nameKh:"ហាស្ស៊ីយ៉ូម",          mass:"(269)",   config:"[Rn] 5f¹⁴ 6d⁶ 7s²",          category:"transition",     period:7, group:8,  useEn:"Synthetic; named for the German state of Hesse.",                       useKh:"សំយោគ; ដាក់ឈ្មោះតាមរដ្ឋហែសនៃប្រទេសអាល្លឺម៉ង់។" },
  { z:109, symbol:"Mt", nameEn:"Meitnerium",   nameKh:"ម៉ៃនេរីយ៉ូម",           mass:"(278)",   config:"[Rn] 5f¹⁴ 6d⁷ 7s²",          category:"unknown",        period:7, group:9,  useEn:"Synthetic; named for Lise Meitner.",                                   useKh:"សំយោគ; ដាក់ឈ្មោះតាម Lise Meitner។" },
  { z:110, symbol:"Ds", nameEn:"Darmstadtium", nameKh:"ដាមស្តាតីយ៉ូម",       mass:"(281)",   config:"[Rn] 5f¹⁴ 6d⁸ 7s²",          category:"unknown",        period:7, group:10, useEn:"Synthetic; named for the German city of Darmstadt.",                   useKh:"សំយោគ; ដាក់ឈ្មោះតាមទីក្រុងដាមស្តាតនៃប្រទេសអាល្លឺម៉ង់។" },
  { z:111, symbol:"Rg", nameEn:"Roentgenium",  nameKh:"រ៉ោនឌែនីយ៉ូម",         mass:"(282)",   config:"[Rn] 5f¹⁴ 6d⁹ 7s²",          category:"unknown",        period:7, group:11, useEn:"Synthetic; named for X-ray discoverer Wilhelm Röntgen.",                useKh:"សំយោគ; ដាក់ឈ្មោះតាម Wilhelm Röntgen ដែលរកឃើញកាំរស្មី X។" },
  { z:112, symbol:"Cn", nameEn:"Copernicium",  nameKh:"កូពែនីស្យូម",         mass:"(285)",   config:"[Rn] 5f¹⁴ 6d¹⁰ 7s²",         category:"unknown",        period:7, group:12, useEn:"Synthetic; named for astronomer Copernicus.",                          useKh:"សំយោគ; ដាក់ឈ្មោះតាមតារាវិទូ Copernicus។" },
  { z:113, symbol:"Nh", nameEn:"Nihonium",     nameKh:"ន៊ីហុនីយ៉ូម",            mass:"(286)",   config:"[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p¹",     category:"unknown",        period:7, group:13, useEn:"Synthetic; named after Japan ('Nihon').",                              useKh:"សំយោគ; ដាក់ឈ្មោះតាមប្រទេសជប៉ុន ('Nihon')។" },
  { z:114, symbol:"Fl", nameEn:"Flerovium",    nameKh:"ហ្វ្លេរ៉ូវីយ៉ូម",          mass:"(289)",   config:"[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p²",     category:"unknown",        period:7, group:14, useEn:"Synthetic; named for the Flerov Lab in Russia.",                       useKh:"សំយោគ; ដាក់ឈ្មោះតាមមន្ទីរពិសោធន៍ Flerov នៅរុស្ស៊ី។" },
  { z:115, symbol:"Mc", nameEn:"Moscovium",    nameKh:"ម៉ូស្កូវីយ៉ូម",            mass:"(290)",   config:"[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p³",     category:"unknown",        period:7, group:15, useEn:"Synthetic; named for Moscow.",                                          useKh:"សំយោគ; ដាក់ឈ្មោះតាមទីក្រុងម៉ូស្គូ។" },
  { z:116, symbol:"Lv", nameEn:"Livermorium",  nameKh:"លីវឺម៉ូរីយ៉ូម",          mass:"(293)",   config:"[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁴",     category:"unknown",        period:7, group:16, useEn:"Synthetic; named for Lawrence Livermore Lab.",                          useKh:"សំយោគ; ដាក់ឈ្មោះតាមមន្ទីរពិសោធន៍ Lawrence Livermore។" },
  { z:117, symbol:"Ts", nameEn:"Tennessine",   nameKh:"តេនណេស៊ីន",            mass:"(294)",   config:"[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁵",     category:"unknown",        period:7, group:17, useEn:"Synthetic; named for the U.S. state of Tennessee.",                    useKh:"សំយោគ; ដាក់ឈ្មោះតាមរដ្ឋតេនណេស៊ីនៃសហរដ្ឋអាមេរិក។" },
  { z:118, symbol:"Og", nameEn:"Oganesson",    nameKh:"អូហ្គាណេសុង",         mass:"(294)",   config:"[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁶",     category:"unknown",        period:7, group:18, useEn:"Heaviest known element; only a few atoms ever made.",                  useKh:"ធាតុធ្ងន់បំផុតដែលគេស្គាល់; មានតែអាតូមមួយចំនួនប៉ុណ្ណោះដែលបានផលិត។" },
];
