import { Brain } from "lucide-react";
import type { SearchEntry } from "@/data/searchTypes";

export const searchMeta: SearchEntry = {
  id: "wellbeing-addiction-science",
  type: "module",
  titleEn: "The Science of Addiction: Hijacking the Brain",
  titleKh: "វិទ្យាសាស្ត្រនៃការញៀន៖ ការលួចបញ្ជាខួរក្បាល",
  descEn:
    "How the brain's dopamine reward system works, how nicotine and other drugs hijack it, why tolerance develops, and why stress so often triggers relapse — explained empathetically and clinically.",
  descKh:
    "របៀបដែលប្រព័ន្ធរង្វាន់ដូប៉ាមីនរបស់ខួរក្បាលដំណើរការ របៀបដែលនីកូទីន និងគ្រឿងញៀនផ្សេងទៀតលួចបញ្ជាវា ហេតុអ្វីបានជាភាពស៊ាំកើតឡើង និងហេតុអ្វីភាពតានតឹងច្រើនតែបង្កការដួលរលំឡើងវិញ — ពន្យល់ដោយការអាណិតអាសូរ និងតាមផ្នែកវេជ្ជសាស្ត្រ។",
  categoryEn: "Public Health",
  categoryKh: "សុខភាពសាធារណៈ",
  href: "/well-being/addiction-science",
  icon: Brain,
  keywordsEn: [
    "addiction",
    "addicted",
    "dopamine",
    "tolerance",
    "withdrawal",
    "cigarette",
    "cigarettes",
    "smoking",
    "nicotine",
    "tobacco",
    "drugs",
    "drug",
    "cocaine",
    "methamphetamine",
    "meth",
    "alcohol",
    "opioid",
    "opioids",
    "heroin",
    "brain",
    "neuroscience",
    "reward system",
    "receptor",
    "synapse",
    "cortisol",
    "stress",
    "relapse",
    "recovery",
    "hijack",
  ],
  keywordsKh: [
    "ការញៀន",
    "ញៀន",
    "ដូប៉ាមីន",
    "ភាពស៊ាំ",
    "បារី",
    "នីកូទីន",
    "ថ្នាំជក់",
    "គ្រឿងញៀន",
    "សារធាតុញៀន",
    "កូកាអ៊ីន",
    "មេតាំហ្វេតាមីន",
    "គ្រឿងស្រវឹង",
    "ខួរក្បាល",
    "ប្រសាទវិទ្យា",
    "កូទីសុល",
    "ភាពតានតឹង",
    "ដួលរលំឡើងវិញ",
    "ការជាសះស្បើយ",
    "រង្វាន់",
    "អ្នកទទួល",
  ],
};
