import { Rocket } from "lucide-react";
import type { SearchEntry } from "@/data/searchTypes";

export const searchMeta: SearchEntry = {
  id: "study-center-entrepreneurship",
  type: "module",
  titleEn: "Entrepreneurship: Building the Future",
  titleKh: "សហគ្រិនភាព៖ ការកសាងអនាគត",
  descEn:
    "What an entrepreneur really is — a problem-solver, not a salesman. Why money is a byproduct of value, why tenacity beats raw talent, and why a single individual with a better system can change the world.",
  descKh:
    "តើសហគ្រិនពិតប្រាកដជាអ្វី — អ្នកដោះស្រាយបញ្ហា មិនមែនអ្នកលក់ទេ។ ហេតុអ្វីប្រាក់គ្រាន់តែជាផលរងនៃតម្លៃ ហេតុអ្វីភាពអត់ធ្មត់ឈ្នះទេពកោសល្យ និងហេតុអ្វីបុគ្គលម្នាក់ដែលមានប្រព័ន្ធល្អជាង អាចផ្លាស់ប្ដូរពិភពលោក។",
  categoryEn: "Study Center",
  categoryKh: "មជ្ឈមណ្ឌលសិក្សា",
  href: "/study-center/entrepreneurship",
  icon: Rocket,
  keywordsEn: [
    "entrepreneurship",
    "entrepreneur",
    "innovation",
    "startup",
    "start-up",
    "founder",
    "business",
    "problem solver",
    "value creation",
    "grit",
    "vision",
    "resilience",
    "tenacity",
    "perseverance",
    "failure",
    "success",
    "mindset",
    "future",
    "build",
    "career",
    "12th grade",
  ],
  keywordsKh: [
    "សហគ្រិនភាព",
    "សហគ្រិន",
    "នវានុវត្តន៍",
    "ស្ថាបនិក",
    "អាជីវកម្ម",
    "អ្នកដោះស្រាយបញ្ហា",
    "ការបង្កើតតម្លៃ",
    "ឆន្ទៈ",
    "ចក្ខុវិស័យ",
    "ភាពធន់",
    "ភាពអត់ធ្មត់",
    "ការតស៊ូ",
    "បរាជ័យ",
    "ជោគជ័យ",
    "ផ្នត់គំនិត",
    "អនាគត",
    "កសាង",
  ],
};
