import { Flame } from "lucide-react";
import type { SearchEntry } from "@/data/searchTypes";

export const searchMeta: SearchEntry = {
  id: "chemistry-flame-test",
  type: "page",
  href: "/chemistry/flame-test",
  icon: Flame,
  titleEn: "The Flame Test — Reading the Colors of Fire",
  titleKh: "ការធ្វើតេស្តអណ្តាតភ្លើង — ការអានពណ៌នៃភ្លើង",
  categoryEn: "Chemistry",
  categoryKh: "គីមីវិទ្យា",
  descEn:
    "Why does copper burn blue-green and sodium burn yellow? The quantum jump that makes every element wear its own color, the equation ΔE = hν, and a glowing color guide to copper, sodium, strontium, and potassium.",
  descKh:
    "ហេតុ​អ្វី​បាន​ជា​ទង់ដែង​ឆេះ​ពណ៌​ខៀវ-បៃតង ហើយ​សូដ្យូម​ឆេះ​ពណ៌​លឿង? ការ​លោត​កង់ទិច​ដែល​ធ្វើ​ឱ្យ​ធាតុ​នីមួយៗ​ស្លៀក​ពណ៌​ផ្ទាល់​ខ្លួន សមីការ ΔE = hν និង​មគ្គុទ្ទេសក៍​ពណ៌​ភ្លឺ​នៃ​ទង់ដែង សូដ្យូម ស្ត្រុងចូម និង​ប៉ូតាស្យូម។",
  keywordsEn: [
    "flame test",
    "flame colors",
    "fire colors",
    "emission spectrum",
    "atomic emission",
    "photon",
    "planck",
    "quantum jump",
    "energy levels",
    "copper",
    "sodium",
    "strontium",
    "potassium",
    "fireworks",
    "Cu",
    "Na",
    "Sr",
    "K",
    "lilac",
    "yellow flame",
    "red flame",
    "blue green flame",
    "spectroscopy",
    "Bunsen burner",
  ],
  keywordsKh: [
    "តេស្តអណ្តាតភ្លើង",
    "ពណ៌​ភ្លើង",
    "ភូតុង",
    "ការ​លោត​កង់ទិច",
    "កម្រិត​ថាមពល",
    "ទង់ដែង",
    "សូដ្យូម",
    "ស្ត្រុងចូម",
    "ប៉ូតាស្យូម",
    "កាំជ្រួច",
    "ផ្លែង",
    "សមីការ​ផ្លែង",
  ],
};
