import { Lightbulb } from "lucide-react";
import type { SearchEntry } from "@/data/searchTypes";

export const searchMeta: SearchEntry = {
  id: "tech-great-inventions",
  type: "module",
  titleEn: "The Builders of Reality: Most Important Inventions in History",
  titleKh: "អ្នកកសាងភាពពិត៖ ការច្នៃប្រឌិតដ៏សំខាន់បំផុតក្នុងប្រវត្តិសាស្ត្រ",
  descEn:
    "Eighteen inventions that built the modern world, grouped into five families: foundations of civilization (fire, agriculture, the wheel, written language); China's four great inventions (papermaking, movable type, gunpowder, the compass); information & communication (printing press, telephone, radio & TV); energy & transportation (electricity, automobile, airplane); and modern science & industry (vaccines & antibiotics, sewing machine, transistor, internet). Filter by category to study one branch at a time.",
  descKh:
    "ការច្នៃប្រឌិតដប់ប្រាំបី ដែលបានសាងសង់ពិភពលោកទំនើប រៀបជាគ្រួសារប្រាំ ៖ មូលដ្ឋានគ្រឹះនៃអរិយធម៌ (ភ្លើង កសិកម្ម កង់ អក្សរសិល្ប៍); ការច្នៃប្រឌិតអស្ចារ្យទាំងបួនរបស់ចិន (ក្រដាស តួអក្សរផ្លាស់ទីបាន ដីកាំភ្លើង ត្រីវិស័យ); ព័ត៌មាន និងទំនាក់ទំនង (ម៉ាស៊ីនបោះពុម្ព ទូរស័ព្ទ វិទ្យុ និងទូរទស្សន៍); ថាមពល និងការដឹកជញ្ជូន (អគ្គិសនី រថយន្ត យន្តហោះ); និងវិទ្យាសាស្ត្រ និងឧស្សាហកម្មទំនើប (វ៉ាក់សាំង និងថ្នាំអង់ទីប៊ីយ៉ូទិច ម៉ាស៊ីនដេរ ត្រង់ស៊ីស្ទ័រ អ៊ីនធឺណែត)។ ច្រោះតាមប្រភេទ ដើម្បីសិក្សាមែកធាងម្ដងមួយ។",
  categoryEn: "Technology",
  categoryKh: "បច្ចេកវិទ្យា",
  href: "/technology/inventions",
  icon: Lightbulb,
  keywordsEn: [
    "invention",
    "inventions",
    "history",
    "fire",
    "agriculture",
    "wheel",
    "writing",
    "written language",
    "papermaking",
    "paper",
    "printing",
    "movable type",
    "gunpowder",
    "compass",
    "China",
    "four great inventions",
    "Gutenberg",
    "printing press",
    "telephone",
    "Bell",
    "radio",
    "television",
    "Marconi",
    "electricity",
    "Tesla",
    "Edison",
    "automobile",
    "Benz",
    "airplane",
    "Wright brothers",
    "vaccine",
    "antibiotic",
    "Jenner",
    "Fleming",
    "penicillin",
    "sewing machine",
    "transistor",
    "Bell Labs",
    "internet",
    "ARPANET",
    "civilization",
    "industrial revolution",
  ],
  keywordsKh: [
    "ការច្នៃប្រឌិត",
    "ច្នៃប្រឌិត",
    "ប្រវត្តិសាស្ត្រ",
    "ភ្លើង",
    "កសិកម្ម",
    "កង់",
    "អក្សរ",
    "អក្សរសិល្ប៍",
    "ក្រដាស",
    "បោះពុម្ព",
    "ដីកាំភ្លើង",
    "ត្រីវិស័យ",
    "ចិន",
    "ការច្នៃប្រឌិតអស្ចារ្យទាំងបួន",
    "ម៉ាស៊ីនបោះពុម្ព",
    "ទូរស័ព្ទ",
    "វិទ្យុ",
    "ទូរទស្សន៍",
    "អគ្គិសនី",
    "រថយន្ត",
    "យន្តហោះ",
    "វ៉ាក់សាំង",
    "ថ្នាំអង់ទីប៊ីយ៉ូទិច",
    "ម៉ាស៊ីនដេរ",
    "ត្រង់ស៊ីស្ទ័រ",
    "អ៊ីនធឺណែត",
    "អរិយធម៌",
    "បដិវត្តន៍ឧស្សាហកម្ម",
  ],
};
