import { Atom } from "lucide-react";
import type { SearchEntry } from "@/data/searchTypes";

export const searchMeta: SearchEntry = {
  id: "chemistry-inorganic-module-04-coordination",
  href: "/science/chemistry/inorganic/coordination",
  icon: Atom,
  titleEn: "Module 4 — Coordination Chemistry",
  titleKh: "មុខវិជ្ជា ៤ — គីមីវិទ្យាកូអរដោនេ",
  categoryEn: "Chemistry · Inorganic 101",
  categoryKh: "គីមីវិទ្យា · អសរីរាង្គ ១០១",
  descEn:
    "Transition metals (iron, copper, cobalt) act as central anchors that trap ligands like claws around them. Hemoglobin holds an iron atom that grabs oxygen. Crystal Field Theory explains the dazzling colors of complexes — d-orbitals split, absorbing specific colors of light.",
  descKh:
    "លោហៈអន្តរការចូល (ដែក ទង់ដែង កូបាល់) ដើរតួជាយុថ្កាកណ្តាលដែលអន្ទាក់លីហ្គង់ជុំវិញខ្លួនដូចក្រញាំ។ ហេម៉ូក្លូប៊ីនកាន់អាតូមដែកដែលចាប់អុកស៊ីសែន។ ទ្រឹស្តីដែនគ្រីស្តាល់ពន្យល់ពណ៌ភ្លឺច្បាស់នៃកុំផ្លិច — d-អ័រប៊ីតាលបំបែក ស្រូបពណ៌ពន្លឺជាក់លាក់។",
  keywordsEn: [
    "coordination chemistry",
    "transition metal",
    "metal complex",
    "ligand",
    "ligands",
    "central metal",
    "iron",
    "copper",
    "cobalt",
    "hemoglobin",
    "heme",
    "oxygen transport",
    "blood",
    "crystal field theory",
    "CFT",
    "d-orbital splitting",
    "octahedral",
    "tetrahedral complex",
    "color of complexes",
    "chlorophyll",
    "cisplatin",
    "chelate",
    "module 04",
    "module 4",
  ],
  keywordsKh: [
    "គីមីវិទ្យាកូអរដោនេ",
    "លោហៈអន្តរការចូល",
    "កុំផ្លិច",
    "លីហ្គង់",
    "ក្រញាំ",
    "ដែក",
    "ទង់ដែង",
    "ហេម៉ូក្លូប៊ីន",
    "ឈាម",
    "អុកស៊ីសែន",
    "ទ្រឹស្តីដែនគ្រីស្តាល់",
    "ពណ៌",
    "ក្លរូហ្វីល",
    "មុខវិជ្ជា ៤",
    "មុខវិជ្ជា ០៤",
  ],
  type: "page",
};
