import { Hexagon } from "lucide-react";
import type { SearchEntry } from "@/data/searchTypes";

export const searchMeta: SearchEntry = {
  id: "chemistry-inorganic-module-03-symmetry-group",
  href: "/science/chemistry/inorganic/symmetry-group",
  icon: Hexagon,
  titleEn: "Module 3 — Symmetry and Group Theory",
  titleKh: "មុខវិជ្ជា ៣ — ទ្រឹស្តីស៊ីមេទ្រី និងក្រុម",
  categoryEn: "Chemistry · Inorganic 101",
  categoryKh: "គីមីវិទ្យា · អសរីរាង្គ ១០១",
  descEn:
    "Group Theory as the mathematics of molecular shape: rotation axes (C_n, spinning like a wheel), mirror planes (sigma, perfect reflection), and inversion centers (i, flip through dead center). Used to predict IR/UV spectra and reactivity.",
  descKh:
    "ទ្រឹស្តីក្រុមជាគណិតវិទ្យានៃទម្រង់ម៉ូលេគុល៖ អ័ក្សវិល (C_n បង្វិលដូចកង់) ប្លង់ឆ្លុះ (sigma ឆ្លុះបញ្ចាំងពេញលេញ) និងចំណុចបញ្ច្រាស (i ត្រឡប់ឆ្លងកាត់ចំណុចកណ្តាល)។ ប្រើដើម្បីព្យាករណ៍ស្ប៉ិចត្រ IR/UV និងប្រតិកម្ម។",
  keywordsEn: [
    "symmetry",
    "group theory",
    "point group",
    "symmetry operations",
    "rotation axis",
    "Cn",
    "C2",
    "C3",
    "mirror plane",
    "sigma plane",
    "sigma v",
    "sigma h",
    "inversion center",
    "improper rotation",
    "character table",
    "molecular symmetry",
    "IR spectroscopy",
    "Raman",
    "UV-Vis",
    "polar molecule",
    "optical activity",
    "module 03",
    "module 3",
  ],
  keywordsKh: [
    "ស៊ីមេទ្រី",
    "ទ្រឹស្តីក្រុម",
    "ប្រតិបត្តិការស៊ីមេទ្រី",
    "អ័ក្សវិល",
    "ប្លង់ឆ្លុះ",
    "ចំណុចបញ្ច្រាស",
    "ក្រុមចំណុច",
    "ម៉ូលេគុល",
    "មុខវិជ្ជា ៣",
    "មុខវិជ្ជា ០៣",
    "កង់",
    "ឆ្លុះ",
    "កណ្តាល",
  ],
  type: "page",
};
