import { Combine } from "lucide-react";
import type { SearchEntry } from "@/data/searchTypes";

export const searchMeta: SearchEntry = {
  id: "chemistry-inorganic-module-02-bonding-molecular",
  href: "/science/chemistry/inorganic/bonding-molecular",
  icon: Combine,
  titleEn: "Module 2 — Bonding & Molecular Theory",
  titleKh: "មុខវិជ្ជា ២ — ទ្រឹស្តីចំណង និងម៉ូលេគុល",
  categoryEn: "Chemistry · Inorganic 101",
  categoryKh: "គីមីវិទ្យា · អសរីរាង្គ ១០១",
  descEn:
    "VSEPR theory and the balloon analogy for molecular shapes (tetrahedral, linear), Molecular Orbital (MO) theory where electron clouds merge across the whole molecule, and Band Theory explaining why metals like copper conduct electricity.",
  descKh:
    "ទ្រឹស្តី VSEPR និងការប្រៀបធៀបជាមួយបាឡុងសម្រាប់ទម្រង់ម៉ូលេគុល (តេត្រាអ៊ែឌ្រាល លីនេអ៊ែរ) ទ្រឹស្តីម៉ូលេគុលអ័រប៊ីតាល (MO) ដែលពពកអេឡិចត្រុងបញ្ចូលគ្នាពេញម៉ូលេគុល និងទ្រឹស្តីបាន់ដែលពន្យល់ហេតុអ្វីលោហៈដូចជាទង់ដែងចម្លងអគ្គិសនី។",
  keywordsEn: [
    "bonding",
    "molecular theory",
    "VSEPR",
    "valence shell electron pair repulsion",
    "balloon analogy",
    "tetrahedral",
    "linear",
    "trigonal planar",
    "bent",
    "molecular orbital",
    "MO theory",
    "bonding orbital",
    "antibonding orbital",
    "band theory",
    "conduction band",
    "valence band",
    "metals conductivity",
    "copper wire",
    "semiconductor",
    "insulator",
    "module 02",
    "module 2",
  ],
  keywordsKh: [
    "ចំណង",
    "ម៉ូលេគុល",
    "VSEPR",
    "ការរុញច្រាននៃគូអេឡិចត្រុង",
    "បាឡុង",
    "តេត្រាអ៊ែឌ្រាល",
    "លីនេអ៊ែរ",
    "ម៉ូលេគុលអ័រប៊ីតាល",
    "ទ្រឹស្តីបាន់",
    "លោហៈ",
    "ទង់ដែង",
    "អគ្គិសនី",
    "ឆ្នុះវិញ្ញាណ",
    "អ៊ីសូឡង់",
    "មុខវិជ្ជា ២",
    "មុខវិជ្ជា ០២",
  ],
  type: "page",
};
