import { Dna } from "lucide-react";
import type { SearchEntry } from "@/data/searchTypes";

export const searchMeta: SearchEntry = {
  id: "chemistry-inorganic-module-06-organometallic",
  href: "/science/chemistry/inorganic/organometallic",
  icon: Dna,
  titleEn: "Module 6 — Organometallic and Bioinorganic Chemistry",
  titleKh: "មុខវិជ្ជា ៦ — គីមីសរីរាង្គលោហៈ និងជីវអសរីរាង្គ",
  categoryEn: "Chemistry · Inorganic 101",
  categoryKh: "គីមីវិទ្យា · អសរីរាង្គ ១០១",
  descEn:
    "How metals teamed up with carbon-based molecules run almost everything alive — and almost every modern factory. Hemoglobin uses an iron (Fe) atom to carry oxygen in your blood. Chlorophyll uses a magnesium (Mg) atom to catch sunlight in every leaf. Organometallic catalysts (Pt, Pd, Rh, Ni) speed up reactions in factories that make plastics, polyester, and medicines without being used up themselves.",
  descKh:
    "របៀបដែលលោហៈរួមដៃជាមួយម៉ូលេគុលផ្អែកលើកាបូនធ្វើការស្ទើរតែគ្រប់របស់មានជីវិត — និងស្ទើរតែគ្រប់រោងចក្រទំនើប។ ហេម៉ូក្លូប៊ីនប្រើអាតូមដែក (Fe) ដឹកអុកស៊ីហ្សែនក្នុងឈាម។ ក្លរូហ្វីលប្រើអាតូមម៉ាញ៉េស្យូម (Mg) ចាប់ពន្លឺថ្ងៃក្នុងស្លឹក។ កាតាលីករសរីរាង្គលោហៈ (Pt, Pd, Rh, Ni) បង្កើនល្បឿនប្រតិកម្មក្នុងរោងចក្រដែលផលិតប្លាស្ទិក ប៉ូលីយ៉េស្ទ័រ និងឱសថ ដោយខ្លួនវាមិនត្រូវបានប្រើអស់។",
  keywordsEn: [
    "organometallic",
    "bioinorganic",
    "bioinorganic chemistry",
    "organometallic chemistry",
    "metal-carbon bond",
    "biological metal",
    "hemoglobin",
    "iron",
    "Fe",
    "blood",
    "oxygen transport",
    "red blood cell",
    "chlorophyll",
    "magnesium",
    "Mg",
    "leaf",
    "photosynthesis",
    "sunlight",
    "plant",
    "rice",
    "catalyst",
    "catalysts",
    "catalysis",
    "organometallic catalyst",
    "platinum",
    "palladium",
    "rhodium",
    "nickel",
    "Pt",
    "Pd",
    "Rh",
    "Ni",
    "catalytic converter",
    "plastic",
    "polyester",
    "medicine",
    "pharmaceutical",
    "module 06",
    "module 6",
  ],
  keywordsKh: [
    "គីមីសរីរាង្គលោហៈ",
    "ជីវអសរីរាង្គ",
    "គីមីវិទ្យាជីវអសរីរាង្គ",
    "ចំណងលោហៈ-កាបូន",
    "លោហៈជីវសាស្ត្រ",
    "ហេម៉ូក្លូប៊ីន",
    "ដែក",
    "ឈាម",
    "អុកស៊ីហ្សែន",
    "កោសិកាឈាមក្រហម",
    "ក្លរូហ្វីល",
    "ម៉ាញ៉េស្យូម",
    "ស្លឹក",
    "សំយោគពន្លឺ",
    "ពន្លឺថ្ងៃ",
    "រុក្ខជាតិ",
    "ស្រូវ",
    "កាតាលីករ",
    "កាតាលីករសរីរាង្គលោហៈ",
    "ផ្លាទីន",
    "កាតាលីទិកខនវឺទ័រ",
    "ប្លាស្ទិក",
    "ប៉ូលីយ៉េស្ទ័រ",
    "ឱសថ",
    "ម៉ាស៊ីនជីវសាស្ត្រ",
    "មុខវិជ្ជា ៦",
    "មុខវិជ្ជា ០៦",
  ],
  type: "page",
};
