import { Activity } from "lucide-react";
import type { SearchEntry } from "@/data/searchTypes";

export const searchMeta: SearchEntry = {
  id: "chemistry-inorganic-module-07-spectroscopy",
  href: "/science/chemistry/inorganic/spectroscopy",
  icon: Activity,
  titleEn: "Module 7 — Spectroscopy & Characterization",
  titleKh: "មុខវិជ្ជា ៧ — វិសាលគមវិទ្យា និងការកំណត់លក្ខណៈ",
  categoryEn: "Chemistry · Inorganic 101",
  categoryKh: "គីមីវិទ្យា · អសរីរាង្គ ១០១",
  descEn:
    "How chemists 'see' molecules that are too small for any microscope: by hitting them with invisible light and reading what bounces back. UV-Visible spectroscopy explains why a copper solution looks blue — electrons absorb red and yellow, only blue passes through. NMR uses the same physics as a hospital MRI machine: a giant magnet plus radio waves let chemists rebuild a molecule's 3D shape atom by atom.",
  descKh:
    "របៀបដែលអ្នកគីមី «មើលឃើញ» ម៉ូលេគុលដែលតូចពេកសម្រាប់មីក្រូទស្សន៍ណាមួយ៖ ដោយការបាញ់ពន្លឺមើលមិនឃើញលើពួកវា និងអានអ្វីដែលឆ្លុះត្រឡប់មកវិញ។ វិសាលគមមើលឃើញអ៊ុលត្រាវីយូឡេពន្យល់ហេតុអ្វីដំណោះស្រាយទង់ដែងមើលទៅខៀវ — អេឡិចត្រុងស្រូបក្រហម និងលឿង មានតែខៀវប៉ុណ្ណោះហុចចេញ។ NMR ប្រើរូបវិទ្យាដូចគ្នានឹងម៉ាស៊ីន MRI នៅមន្ទីរពេទ្យ៖ ម៉ាញ៉េតយក្សបូករួមនឹងរលកវិទ្យុអនុញ្ញាតឱ្យអ្នកគីមីសង់ឡើងវិញនូវរូបរាងបីវិមាត្រនៃម៉ូលេគុលអាតូមម្តងមួយ។",
  keywordsEn: [
    "spectroscopy",
    "characterization",
    "spectrum",
    "electromagnetic spectrum",
    "UV-Vis",
    "UV-Visible",
    "ultraviolet",
    "visible light",
    "absorption",
    "absorbance",
    "color",
    "copper sulfate",
    "blue solution",
    "permanganate",
    "Cu",
    "NMR",
    "nuclear magnetic resonance",
    "MRI",
    "magnetic resonance imaging",
    "magnet",
    "radio waves",
    "echo",
    "3D structure",
    "molecular structure",
    "hydrogen NMR",
    "proton NMR",
    "1H NMR",
    "infrared",
    "IR",
    "instrument",
    "analytical method",
    "module 07",
    "module 7",
  ],
  keywordsKh: [
    "វិសាលគមវិទ្យា",
    "វិសាលគម",
    "ការកំណត់លក្ខណៈ",
    "វិសាលគមមើលឃើញអ៊ុលត្រាវីយូឡេ",
    "អ៊ុលត្រាវីយូឡេ",
    "ពន្លឺមើលឃើញ",
    "ការស្រូប",
    "ពណ៌",
    "ស៊ុលហ្វាតទង់ដែង",
    "ដំណោះស្រាយទង់ដែង",
    "អនុភាពម៉ាញេទិកនុយក្លេអ៊ែរ",
    "MRI",
    "ម៉ាញ៉េត",
    "រលកវិទ្យុ",
    "សំឡេងបន្ទរ",
    "រូបរាងបីវិមាត្រ",
    "រចនាសម្ព័ន្ធម៉ូលេគុល",
    "អ៊ីដ្រូសែន",
    "ការថតរូបអាតូម",
    "មុខវិជ្ជា ៧",
    "មុខវិជ្ជា ០៧",
  ],
  type: "page",
};
