import { Grid3x3 } from "lucide-react";
import type { SearchEntry } from "@/data/searchTypes";

export const searchMeta: SearchEntry = {
  id: "chemistry-inorganic-module-05-main-group",
  href: "/science/chemistry/inorganic/main-group",
  icon: Grid3x3,
  titleEn: "Module 5 — Main Group Element Chemistry",
  titleKh: "មុខវិជ្ជា ៥ — គីមីវិទ្យាធាតុក្រុមចម្បង",
  categoryEn: "Chemistry · Inorganic 101",
  categoryKh: "គីមីវិទ្យា · អសរីរាង្គ ១០១",
  descEn:
    "The s-block and p-block elements that make up almost everything we touch, breathe, and eat. Alkali metals (Group 1) like sodium give away electrons to form table salt. Halogens (Group 17) like chlorine steal electrons, which is why bleach kills bacteria. Noble gases (Group 18) like helium have full outer shells and are unreactive — perfect for party balloons and neon signs.",
  descKh:
    "ធាតុ s-block និង p-block ដែលបង្កើតបានស្ទើរតែគ្រប់អ្វីៗដែលយើងប៉ះពាល់ ដកដង្ហើម និងបរិភោគ។ លោហៈអាល់កាឡាំង (ក្រុម ១) ដូចជាសូដ្យូមផ្តល់អេឡិចត្រុងបង្កើតជាអំបិល។ ហាឡូសែន (ក្រុម ១៧) ដូចជាក្លរីនលួចអេឡិចត្រុង ដូច្នេះសារធាតុបក្ខាងសម្លាប់បាក់តេរី។ ឧស្ម័នកម្រ (ក្រុម ១៨) ដូចជាអេលីយ៉ូមមានសែលខាងក្រៅពេញ និងមិនមានប្រតិកម្ម — សុក្រឹដ្យសម្រាប់ប៉ោងពិធីបុណ្យ និងផ្លាកនេអុង។",
  keywordsEn: [
    "main group",
    "main group elements",
    "main group chemistry",
    "s-block",
    "p-block",
    "periodic table",
    "alkali metals",
    "group 1",
    "sodium",
    "potassium",
    "lithium",
    "Na",
    "K",
    "Li",
    "table salt",
    "NaCl",
    "fertilizer",
    "NPK",
    "halogens",
    "group 17",
    "chlorine",
    "fluorine",
    "iodine",
    "bromine",
    "Cl",
    "F",
    "I",
    "bleach",
    "water purification",
    "drinking water",
    "fluoride",
    "toothpaste",
    "noble gases",
    "group 18",
    "helium",
    "neon",
    "argon",
    "He",
    "Ne",
    "Ar",
    "balloon",
    "neon sign",
    "light bulb",
    "inert gas",
    "non-reactive",
    "electron giver",
    "electron stealer",
    "module 05",
    "module 5",
  ],
  keywordsKh: [
    "ក្រុមចម្បង",
    "ធាតុក្រុមចម្បង",
    "គីមីវិទ្យាធាតុក្រុមចម្បង",
    "s-block",
    "p-block",
    "តារាងខួប",
    "លោហៈអាល់កាឡាំង",
    "ក្រុម ១",
    "សូដ្យូម",
    "ប៉ូតាស្យូម",
    "លីធីយ៉ូម",
    "អំបិល",
    "ជី",
    "ហាឡូសែន",
    "ក្រុម ១៧",
    "ក្លរីន",
    "ហ្វ្លុយអូរីន",
    "អ៊ីយ៉ូត",
    "សារធាតុបក្ខាង",
    "ទឹកផឹក",
    "ហ្វ្លុយអូរីដ",
    "ថ្នាំដុសធ្មេញ",
    "ឧស្ម័នកម្រ",
    "ក្រុម ១៨",
    "អេលីយ៉ូម",
    "នេអុង",
    "អាហ្គន",
    "ប៉ោង",
    "ផ្លាកនេអុង",
    "អំពូលភ្លើង",
    "មុខវិជ្ជា ៥",
    "មុខវិជ្ជា ០៥",
  ],
  type: "page",
};
