import { KeyRound } from "lucide-react";
import type { SearchEntry } from "@/data/searchTypes";

export const searchMeta: SearchEntry = {
  id: "tech-locks-keys",
  type: "module",
  titleEn: "Locks & Keys: Mechanical Passwords",
  titleKh: "សោរ និងកូនសោរ៖ ពាក្យសម្ងាត់មេកានិច",
  descEn:
    "How the world's most common lock — the pin tumbler — works. The shear line that physically blocks the cylinder, why every cut on a key is a digit in a mechanical password, and the four skills (micro-mechanics, spatial reasoning, metalworking, electronics) that make a locksmith a real security engineer.",
  descKh:
    "របៀបដែលសោរដែលប្រើច្រើនបំផុតនៅលើពិភពលោក — សោរម្ជុលកន្លាស់ — ដំណើរការ។ ខ្សែបន្ទាត់កាត់ដែលបិទស៊ីឡាំងដោយរូបវិទ្យា ហេតុអ្វីការកាត់នីមួយៗលើកូនសោរគឺជាលេខមួយក្នុងពាក្យសម្ងាត់មេកានិច និងជំនាញទាំងបួន (មីក្រូ-មេកានិច ការវែកញែកអំពីលំហ ជំនាញលោហៈ និងអេឡិចត្រូនិក) ដែលធ្វើឱ្យជាងសោរជាវិស្វករសុវត្ថិភាពពិតប្រាកដ។",
  categoryEn: "Technology",
  categoryKh: "បច្ចេកវិទ្យា",
  href: "/technology/locks",
  icon: KeyRound,
  keywordsEn: [
    "lock",
    "locks",
    "key",
    "keys",
    "padlock",
    "locksmith",
    "locksmithing",
    "pin tumbler",
    "shear line",
    "cylinder",
    "deadbolt",
    "Yale",
    "mechanical password",
    "physical security",
    "smart lock",
    "vault",
    "safe",
    "security engineer",
    "master key",
  ],
  keywordsKh: [
    "សោរ",
    "កូនសោរ",
    "ជាងសោរ",
    "សោរម្ជុលកន្លាស់",
    "ខ្សែបន្ទាត់កាត់",
    "ស៊ីឡាំង",
    "ស្ពាន់សោរ",
    "ពាក្យសម្ងាត់មេកានិច",
    "សុវត្ថិភាពរូបវន្ត",
    "សោរឆ្លាតវ័យ",
    "ទូដាក់ប្រាក់",
    "វិស្វករសុវត្ថិភាព",
  ],
};
