import { Brain } from "lucide-react";
import type { SearchEntry } from "@/data/searchTypes";

export const searchMeta: SearchEntry = {
  id: "medicine-mcat",
  type: "module",
  titleEn: "The MCAT: The Medical Marathon",
  titleKh: "ការប្រឡង MCAT៖ ម៉ារ៉ាតុងវេជ្ជសាស្ត្រ",
  descEn:
    "The 7.5-hour exam that decides who gets into medical school in the US, Canada and the Caribbean (and a smaller number of programs elsewhere). What's tested (Bio, Chem, Physics, Psych, Soc, CARS), why active recall beats passive reading, and the 300–500 hour timeline.",
  descKh:
    "ការប្រឡងរយៈពេល ៧.៥ ម៉ោង ដែលសម្រេចថានរណាបានចូលរៀនពេទ្យនៅ សហរដ្ឋអាមេរិក កាណាដា និងការ៉ាប៊ីន (និងកម្មវិធីមួយចំនួនតូចនៅប្រទេសផ្សេងទៀត)។ អ្វីដែលត្រូវប្រឡង (ជីវវិទ្យា គីមី រូបវិទ្យា ចិត្តវិទ្យា សង្គមវិទ្យា CARS) ហេតុអ្វីការរំលឹកសកម្មឈ្នះការអានអសកម្ម និងពេលវេលា ៣០០–៥០០ ម៉ោង។",
  categoryEn: "Medicine",
  categoryKh: "វេជ្ជសាស្ត្រ",
  href: "/pathway-to-medicine/mcat",
  icon: Brain,
  keywordsEn: [
    "MCAT",
    "medical college admission test",
    "medical school",
    "med school",
    "premed",
    "pre-med",
    "USMLE",
    "doctor exam",
    "AAMC",
    "active recall",
    "Anki",
    "spaced repetition",
    "CARS",
    "critical reading",
    "biology",
    "chemistry",
    "organic chemistry",
    "physics",
    "psychology",
    "sociology",
    "junior year",
    "premed timeline",
    "study plan",
    "marathon test",
    "7.5 hours",
  ],
  keywordsKh: [
    "MCAT",
    "ការប្រឡងពេទ្យ",
    "សាកលវិទ្យាល័យពេទ្យ",
    "វេជ្ជសាស្ត្រ",
    "ការរំលឹកសកម្ម",
    "Anki",
    "CARS",
    "ការអានវិភាគ",
    "ជីវវិទ្យា",
    "គីមី",
    "គីមីសរីរាង្គ",
    "រូបវិទ្យា",
    "ចិត្តវិទ្យា",
    "សង្គមវិទ្យា",
    "ឆ្នាំទី ៣",
    "ផែនការសិក្សា",
    "ម៉ារ៉ាតុង",
  ],
};
