import { Recycle } from "lucide-react";
import type { SearchEntry } from "@/data/searchTypes";

export const searchMeta: SearchEntry = {
  id: "materials-recycling",
  type: "module",
  titleEn: "Recycling: The Energy Economics of Trash",
  titleKh: "ការកែច្នៃឡើងវិញ៖ សេដ្ឋកិច្ចថាមពលនៃសំរាម",
  descEn:
    "Why recycling aluminum saves 95% of the energy of mining, how Cambodia's Edjai waste-pickers form the country's frontline recycling network, and the 3-step entrepreneurial pathway to starting a recycling business.",
  descKh:
    "ហេតុអ្វីការកែច្នៃអាលុយមីញ៉ូមសន្សំ ៩៥% នៃថាមពលនៃការជីករ៉ែ របៀបដែលអ្នករើសសំរាមអេតចាយរបស់កម្ពុជា បង្កើតបានជាបណ្ដាញកែច្នៃជួរមុខរបស់ប្រទេស និងមាគ៌ាសហគ្រិន ៣ ជំហានសម្រាប់ការចាប់ផ្ដើមអាជីវកម្មកែច្នៃ។",
  categoryEn: "Materials Science",
  categoryKh: "វិទ្យាសាស្ត្រសម្ភារៈ",
  href: "/science/materials/recycling",
  icon: Recycle,
  keywordsEn: [
    "recycling",
    "recycle",
    "recycled",
    "energy",
    "trash",
    "waste",
    "aluminum",
    "aluminium",
    "steel",
    "iron",
    "glass",
    "plastic",
    "PET",
    "HDPE",
    "downcycling",
    "smelting",
    "mining",
    "Edjai",
    "waste pickers",
    "scrap",
    "bauxite",
    "rebar",
    "bale",
    "baling",
    "sorting",
    "circular economy",
    "Cambodia",
    "business",
    "entrepreneur",
    "12th grade",
  ],
  keywordsKh: [
    "កែច្នៃ",
    "ការកែច្នៃឡើងវិញ",
    "ថាមពល",
    "សំរាម",
    "កាកសំណល់",
    "អាលុយមីញ៉ូម",
    "ដែក",
    "ដែកថែប",
    "កញ្ចក់",
    "ប្លាស្ទិក",
    "PET",
    "ការរលាយ",
    "ការជីករ៉ែ",
    "អេតចាយ",
    "អ្នករើសសំរាម",
    "ដុំបាល",
    "ច្រេប",
    "កម្ពុជា",
    "អាជីវកម្ម",
    "សហគ្រិន",
    "ថ្នាក់ទី១២",
  ],
};
