import { PawPrint } from "lucide-react";
import type { SearchEntry } from "@/data/searchTypes";

export const searchMeta: SearchEntry = {
  id: "science-veterinary",
  type: "page",
  href: "/science/veterinary",
  icon: PawPrint,
  titleEn: "Veterinary Medicine — Healing the Animal Kingdom",
  titleKh: "ពេទ្យសត្វ — ការព្យាបាលសត្វ",
  categoryEn: "Science",
  categoryKh: "វិទ្យាសាស្ត្រ",
  descEn:
    "Animal doctors who perform surgery, deliver newborns, and stop zoonotic diseases like Rabies and Bird Flu — the high-school-to-DVM pathway, plus a patient ward of cattle, pigs, poultry, dogs and cats.",
  descKh:
    "គ្រូពេទ្យសត្វដែលធ្វើវះកាត់ ជួយសម្រាលកូនសត្វ និងបញ្ឈប់ជំងឺហ្សូណូទិកដូចជាឆ្កែឆ្កួត និងផ្តាសាយបក្សី — ផ្លូវសិក្សាពីវិទ្យាល័យដល់ DVM ព្រមទាំងបន្ទប់អ្នកជំងឺនៃគោ ក្របី ជ្រូក មាន់ ឆ្កែ និងឆ្មា។",
  keywordsEn: [
    "veterinary",
    "veterinarian",
    "vet",
    "animal doctor",
    "animals",
    "livestock",
    "zoonotic",
    "rabies",
    "bird flu",
    "avian influenza",
    "newcastle",
    "african swine fever",
    "asf",
    "foot and mouth",
    "bloat",
    "parasites",
    "cattle",
    "buffalo",
    "pigs",
    "poultry",
    "chickens",
    "dogs",
    "cats",
    "DVM",
    "animal science",
  ],
  keywordsKh: [
    "ពេទ្យសត្វ",
    "សត្វ",
    "ហ្សូណូទិក",
    "ឆ្កែឆ្កួត",
    "ផ្តាសាយបក្សី",
    "ប៉េស្តជ្រូកអាហ្វ្រិក",
    "ជំងឺអុតក្តាម",
    "គោ",
    "ក្របី",
    "ជ្រូក",
    "មាន់",
    "ឆ្កែ",
    "ឆ្មា",
    "សត្វចិញ្ចឹម",
    "កសិដ្ឋាន",
  ],
};
