import { Router, type IRouter } from "express";
import healthRouter from "./health";
import schoolsRouter from "./schools";
import needsRouter from "./needs";
import completedProjectsRouter from "./completedProjects";
import uploadRouter from "./upload";
import authRouter from "./auth";
import storiesRouter from "./stories";
import openaiRouter from "./openai";
import interviewRouter from "./interview";
import adminMetricsRouter from "./adminMetrics";
import savedCareersRouter from "./savedCareers";
import quizRouter from "./quiz";
import leaderboardRouter from "./leaderboard";
import skepticRouter from "./skeptic";
import booksRouter from "./books";
import authorsRouter from "./authors";
import achievementsRouter from "./achievements";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(schoolsRouter);
router.use(needsRouter);
router.use(completedProjectsRouter);
router.use(uploadRouter);
router.use(storiesRouter);
router.use(openaiRouter);
router.use(interviewRouter);
router.use(adminMetricsRouter);
router.use(savedCareersRouter);
router.use(quizRouter);
router.use(leaderboardRouter);
router.use(skepticRouter);
router.use(booksRouter);
router.use(authorsRouter);
router.use(achievementsRouter);

export default router;
