import { Router, type IRouter } from "express";
import healthRouter from "./health";
import schoolsRouter from "./schools";
import needsRouter from "./needs";
import completedProjectsRouter from "./completedProjects";
import schoolMessagesRouter from "./schoolMessages";
import notificationsRouter from "./notifications";
import storiesRouter from "./stories";
import uploadRouter from "./upload";
import authRouter from "./auth";
import adminMetricsRouter from "./adminMetrics";
const router: IRouter = Router();
router.use(healthRouter);
router.use(schoolsRouter);
router.use(needsRouter);
router.use(completedProjectsRouter);
router.use(schoolMessagesRouter);
router.use(notificationsRouter);
router.use(storiesRouter);
router.use(uploadRouter);
router.use(authRouter);
router.use(adminMetricsRouter);
export default router;
